// <auto-generated />
using System.Collections.Generic;
using BnDapi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BnDapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230324014522_updateDuAndetail")]
    partial class updateDuAndetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BnDapi.Models.DuAnImgae", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DuanId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageA")
                        .HasColumnType("text");

                    b.Property<string>("ImageB")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DuanId");

                    b.ToTable("DuAnImgae");
                });

            modelBuilder.Entity("BnDapi.Models.Duan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("ImageB")
                        .HasColumnType("text");

                    b.Property<List<string>>("ListImg")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Duans");
                });

            modelBuilder.Entity("BnDapi.Models.DuAnImgae", b =>
                {
                    b.HasOne("BnDapi.Models.Duan", "Duan")
                        .WithMany("DuAnImgae")
                        .HasForeignKey("DuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duan");
                });

            modelBuilder.Entity("BnDapi.Models.Duan", b =>
                {
                    b.Navigation("DuAnImgae");
                });
#pragma warning restore 612, 618
        }
    }
}
